# Gitbook with R Markdown

##### Author: Jason Bryer [jason@bryer.org](mailto:jason@bryer.org)  
##### Website: [jason.bryer.org/Rgitbook](http://jason.bryer.org/Rgitbook)  
##### Repository: [github.com/jbryer/Rgitbook/tree/master](https://github.com/jbryer/Rgitbook/tree/master)  

[Gitbook](http://gitbook.io) is a Node.js framework for developing/writing books using [Markdown](https://daringfireball.net/projects/markdown/). Using the same source markdown files, it can generate books in web, PDF, eBook, and JSON formats. More information about Gitbook is available at their website at [www.gitbook.io/](http://www.gitbook.io/).

This page describes an [R](http://www.r-project.org) package that interfaces with Gitbook for generating books using R markdown. Virtually all aspects of developing Gitbooks can be done in R. [RStudio](http://rstudio.com) is a particulary nice Integrated Development Environment (IDE) for workting with R and R Markdown. This book, created using Gitbook and the `Rgitbook` R package, will describe the process of book development.

This book in fact uses the Gitbook.io framework and `Rgitbook` R package. You can browse the source code at [Github](https://github.com/jbryer/Rgitbook/tree/master/website) and the R script to build the book and R package [here](https://github.com/jbryer/Rgitbook/tree/master).

